import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type DocConfig = {
  source: string;
  target: string;
  title: string;
  intro: string;
  stripRepoNote?: boolean;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");
const publicDir = path.resolve(scriptDir, "..", "public");

const docs: DocConfig[] = [
  {
    source: "ONE_REQUEST_API.md",
    target: "one-request-api.md",
    title: "# Boreal One-Request API",
    intro: "This public file mirrors Boreal's live agent-only request-first contract.",
  },
  {
    source: "ONE_INBOX_API.md",
    target: "one-inbox-api.md",
    title: "# Boreal One-Inbox API",
    intro: "This public file mirrors Boreal's live supplier-side contract.",
  },
  {
    source: "AGENT-REGISTRY.md",
    target: "agent-registry.md",
    title: "# Boreal Public Agent Registry",
    intro: "This public file mirrors Boreal's advanced specialist registry contract.",
    stripRepoNote: true,
  },
  {
    source: "HERMES_CONNECT_QUICKSTART.md",
    target: "connect-agent-quickstart.md",
    title: "# Boreal Connect-Agent Quickstart",
    intro: "This public file mirrors Boreal's shortest live quickstart for advanced connected runtimes and local model bridges.",
  },
];

const publicNameMap = new Map<string, string>([
  ["ONE_REQUEST_API.md", "one-request-api.md"],
  ["ONE_INBOX_API.md", "one-inbox-api.md"],
  ["AGENT-REGISTRY.md", "agent-registry.md"],
  ["HERMES_CONNECT_QUICKSTART.md", "connect-agent-quickstart.md"],
]);

function stripFirstHeading(markdown: string) {
  return markdown.replace(/^# .+\r?\n+/, "");
}

function stripAgentRegistryRepoNote(markdown: string) {
  const repoNoteIndex = markdown.indexOf("Repo note:");
  const purposeIndex = markdown.indexOf("## Purpose");

  if (repoNoteIndex === -1 || purposeIndex === -1 || purposeIndex <= repoNoteIndex) {
    return markdown;
  }

  const before = markdown.slice(0, repoNoteIndex).trimEnd();
  const after = markdown.slice(purposeIndex).trimStart();
  return `${before}\n\n${after}`;
}

function rewritePublicReferences(markdown: string) {
  let output = markdown;

  for (const [sourceName, publicName] of publicNameMap.entries()) {
    output = output.replaceAll(sourceName, publicName);
  }

  return output;
}

async function syncDoc(config: DocConfig) {
  const sourcePath = path.resolve(repoRoot, config.source);
  const targetPath = path.resolve(publicDir, config.target);
  const sourceMarkdown = await readFile(sourcePath, "utf8");

  let body = stripFirstHeading(sourceMarkdown).trimStart();

  if (config.stripRepoNote) {
    body = stripAgentRegistryRepoNote(body).trimStart();
  }

  body = rewritePublicReferences(body).trim();

  const generated = [
    config.title,
    "",
    `> Generated from \`${config.source}\` by \`npm run docs:sync:public\`.  Do not edit this file by hand.`,
    "",
    config.intro,
    "",
    body,
    "",
  ].join("\n");

  await writeFile(targetPath, generated, "utf8");
  return config.target;
}

async function main() {
  await mkdir(publicDir, { recursive: true });
  const written = await Promise.all(docs.map(syncDoc));
  for (const file of written) {
    console.log(`synced ${file}`);
  }
}

await main();
