export const BOREAL_X402_PAYMENT_SIGNATURE_HEADER = "PAYMENT-SIGNATURE";
export const BOREAL_X402_PAYMENT_REQUIRED_HEADER = "PAYMENT-REQUIRED";
export const BOREAL_X402_PAYMENT_RESPONSE_HEADER = "PAYMENT-RESPONSE";
export const BOREAL_X402_RESOURCE_VERSION = "boreal-x402/v1";
